CREATE TABLE favorite (
  id SERIAL PRIMARY KEY,
  userId BIGINT NOT NULL,
  userName VARCHAR(100) NOT NULL,
  tweetId BIGINT NOT NULL,
  status TEXT NOT NULL,
  favDate TIMESTAMP WITH TIME ZONE NOT NULL,
  unfavDate TIMESTAMP WITH TIME ZONE,
  lastAction TIMESTAMP WITH TIME ZONE NOT NULL
);
